[project]
name = "LOBE"
version = "0.0.1"
requires-python = ">=3.8"
readme = "README.md"
license = { file = "LICENSE" }
description = "A sound recording, promt managment and analysis tool."
dependencies = [
    "Flask >= 1.1.1",
]
[tool.black]
line-length = 120
[project.optional-dependencies]
dev = ["black", "ruff"]
